### ISSUE TITLE
Does it support JavaScript enabled website for automation?

### ISSUE THREAD

**Issue by rahulmr** [jelford/activesoup#7]
Does it support JavaScript enabled website for automation?

```python

>>> import activesoup
>>> d = activesoup.Driver()
>>> page = d.get("https://kite.zerodha.com")
>>> form = page.form
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\trading\headless_browser_automation\venv\lib\site-packages\activesoup\driver.py", line 87, in __getattr__
    return getattr(self.last_response, item)
  File "D:\trading\headless_browser_automation\venv\lib\site-packages\activesoup\html.py", line 40, in __getattr__
    raise AttributeError(f"{type(self)} has no attribute {item}")
AttributeError: <class 'activesoup.html.BoundTag'> has no attribute form
```

**Comment by jelford** [comment]
Hi @rahulmr , thanks for trying `activesoup`. Unfortunately JavaScript isn't supported. If you need that, I suggest you take a look at one of:
- [requests-html](https://requests-html.kennethreitz.org/)
- [phantomjs](https://github.com/ariya/phantomjs) (though this looks to no longer be under active development)
- [Selenium WebDriver](https://www.selenium.dev/documentation/en/webdriver/)

In general, these projects need a browser of some kind to evaluate JavaScript for them - such a requirement makes this out of scope for `activesoup` I'm afraid.

Hopefully you can get some success with one of those tools - best of luck
